package com.d1m.wechat.common;

/**
 * Constant
 *
 * @author f0rb on 2017-02-15.
 */
public interface Constant {

    byte STATUS_INVALID = 0;//状态:无效

    byte STATUS_VALID = 1;//状态:有效

    String CUSTOMER_TOKEN = "customerToken";

    String AC_KEY = "ackey";

    String TOKEN = "token";

    String TIMESTAMP = "timestamp";

    String SIGN = "sign";

    Integer EXPIRED_MINS = 10;

    String ZEGNA_SECRET = "secret";

    String CHARSET_UTF_8 = "UTF-8";

    String WECHAT_MESSAGE_PATH_EVENT = "xml/Event";

    String ZEGNA_CAMPAIGN_RED = "ZEGNA_CAMPAIGN_RED";

    String ZEGNA_CAMPAIGN_NOTIFICATION = "ZEGNA_CAMPAIGN_NOTIFICATION";
    String RED_NOTIFICATION_MESSAGE = "RED_NOTIFICATION_MESSAGE";

    String REGISTER_ROUTINE = "REGISTER_ROUTINE";
    String REGISTER_CNY_NORMAL = "REGISTER_CNY_NORMAL";
    String REGISTER_CNY_LACK = "REGISTER_CNY_LACK";
    String PROFILE_BIND_ROUTINE = "PROFILE_BIND_ROUTINE";
    String PROFILE_BIND_NORMAL = "PROFILE_BIND_NORMAL";
    String PROFILE_BIND_LACK = "PROFILE_BIND_LACK";
    String PROFILE_INFO_ROUTINE = "PROFILE_INFO_ROUTINE";
    String PROFILE_INFO_NORMAL = "PROFILE_INFO_NORMAL";
    String PROFILE_INFO_LACK = "PROFILE_INFO_LACK";
    String CAMPAIGN_STATUS = "CAMPAIGN_STATUS";
    String CAMPAIGN_DATETIME = "CAMPAIGN_DATETIME";
    String REDEEMED_NORMAL = "REDEEMED_NORMAL";
    String BOUTIQUE_CODE = "BOUTIQUE_CODE";
    String CONFIRM_BUTTON = "CONFIRM_BUTTON";
    String CLOSE_BUTTON = "CLOSE_BUTTON";

    String PROFILE_RETURN_ROUTINE_BTN = "PROFILE_RETURN_ROUTINE_BTN";

    String PROFILE_RETURN_NORMAL_BTN = "PROFILE_RETURN_NORMAL_BTN";

    String PROFILE_RETURN_LACK_BTN = "PROFILE_RETURN_LACK_BTN";
    String PROFILE_NEXT_LACK_BTN = "PROFILE_NEXT_LACK_BTN";

    String PROFILE_NEXT_NORMAL_BTN = "PROFILE_NEXT_NORMAL_BTN";

    String PROFILE_NEXT_ROUTINE_BTN = "PROFILE_NEXT_ROUTINE_BTN";

    String REDEEMED_BUTTON = "REDEEMED_BUTTON";

    String REDEEMED_CONFIRM_BUTTON = "REDEEMED_CONFIRM_BUTTON";

    String PROFILE_NO_USER_TIP ="PROFILE_NO_USER_TIP";

    String PROFILE_NO_USER_CLOSE_BTN="PROFILE_NO_USER_CLOSE_BTN";

    String PROFILE_NO_USER_EDIT_BTN="PROFILE_NO_USER_EDIT_BTN";

    String VALID ="valid";

    String USED = "used";

    String EXPIRED = "expired";

    String CNY_TAG_NAME="2018CNY";

    String MAC_TAG_NAME="MacauVoucher";

    String MAC_CNY_TAG_NAME="Mac&2018CNY";

}
